package contact

import (
	"errors"
)

var (
	ErrContactNotFound           error = errors.New("contact not found")
	ErrContactReadOnly           error = errors.New("contact is read-only")
	ErrContactAddressNotFound    error = errors.New("contact address not found")
	ErrContactAddressIsDefault   error = errors.New("contact address is default")
	ErrContactEmailNotFound      error = errors.New("contact email not found")
	ErrContactEmailIsDefault     error = errors.New("contact email is default")
	ErrContactPhoneNotFound      error = errors.New("contact phone not found")
	ErrContactPhoneIsDefault     error = errors.New("contact phone is default")
	ErrContactUriNotFound        error = errors.New("contact uri not found")
	ErrContactUriIsDefault       error = errors.New("contact uri is default")
	ErrCompanyNotFound           error = errors.New("company not found")
	ErrCompanyReadOnly           error = errors.New("company is read-only")
	ErrCompanyAddressNotFound    error = errors.New("company address not found")
	ErrCompanyAddressIsDefault   error = errors.New("company address is default")
	ErrCompanyEmailNotFound      error = errors.New("company email not found")
	ErrCompanyEmailIsDefault     error = errors.New("company email is default")
	ErrCompanyPhoneNotFound      error = errors.New("company phone not found")
	ErrCompanyPhoneIsDefault     error = errors.New("company phone is default")
	ErrCompanyUriNotFound        error = errors.New("company uri not found")
	ErrCompanyUriIsDefault       error = errors.New("company uri is default")
	ErrAddressTypeNotFound       error = errors.New("address type not found")
	ErrAddressTypeDuplicateKey   error = errors.New("address type with same key already exists")
	ErrAddressTypeDuplicateName  error = errors.New("address type with same language/name already exists")
	ErrAddressTypeReadOnly       error = errors.New("address type is read-only")
	ErrAddressTypeIsDefault      error = errors.New("address type is default")
	ErrEmailTypeNotFound         error = errors.New("email type not found")
	ErrEmailTypeDuplicateKey     error = errors.New("email type with same key already exists")
	ErrEmailTypeDuplicateName    error = errors.New("email type with same language/name already exists")
	ErrEmailTypeReadOnly         error = errors.New("email type is read-only")
	ErrEmailTypeIsDefault        error = errors.New("email type is default")
	ErrPhoneTypeNotFound         error = errors.New("phone type not found")
	ErrPhoneTypeDuplicateKey     error = errors.New("phone type with same key already exists")
	ErrPhoneTypeDuplicateName    error = errors.New("phone type with same language/name already exists")
	ErrPhoneTypeReadOnly         error = errors.New("phone type is read-only")
	ErrPhoneTypeIsDefault        error = errors.New("phone type is default")
	ErrUriTypeNotFound           error = errors.New("uri type not found")
	ErrUriTypeDuplicateKey       error = errors.New("uri type with same key already exists")
	ErrUriTypeDuplicateName      error = errors.New("uri type with same language/name already exists")
	ErrUriTypeReadOnly           error = errors.New("uri type is read-only")
	ErrUriTypeIsDefault          error = errors.New("uri type is default")
	ErrContactTitleNotFound      error = errors.New("contact title not found")
	ErrContactTitleDuplicateKey  error = errors.New("contact title with same key already exists")
	ErrContactTitleDuplicateName error = errors.New("contact title with same language/name already exists")
	ErrContactTitleReadOnly      error = errors.New("contact title is read-only")
	ErrJobTitleNotFound          error = errors.New("job title not found")
	ErrJobTitleDuplicateKey      error = errors.New("job title with same key already exists")
	ErrJobTitleDuplicateName     error = errors.New("job title with same language/name already exists")
	ErrJobTitleReadOnly          error = errors.New("job title is read-only")
	ErrCompanyTypeNotFound       error = errors.New("company type not found")
	ErrCompanyTypeDuplicateKey   error = errors.New("company type with same key already exists")
	ErrCompanyTypeDuplicateName  error = errors.New("company type with same language/name already exists")
	ErrCompanyTypeReadOnly       error = errors.New("company type is read-only")
	ErrIndustryNotFound          error = errors.New("industry not found")
	ErrIndustryDuplicateKey      error = errors.New("industry with same key exists")
	ErrIndustryDuplicateName     error = errors.New("industry with same language/name already exists")
	ErrIndustryReadOnly          error = errors.New("industry is read-only")
)
