package contact

import "errors"

var (
	ErrContactNotFound          error = errors.New("contact not found")
	ErrContactAddressNotFound   error = errors.New("contact address not found")
	ErrContactEmailNotFound     error = errors.New("contact email not found")
	ErrContactPhoneNotFound     error = errors.New("contact phone not found")
	ErrContactUriNotFound       error = errors.New("contact uri not found")
	ErrCompanyNotFound          error = errors.New("company not found")
	ErrCompanyAddressNotFound   error = errors.New("company address not found")
	ErrCompanyEmailNotFound     error = errors.New("company email not found")
	ErrCompanyPhoneNotFound     error = errors.New("company phone not found")
	ErrCompanyUriNotFound       error = errors.New("company uri not found")
	ErrAddressTypeNotFound      error = errors.New("address type not found")
	ErrAddressTypeDuplicateKey  error = errors.New("address type with same key already exists")
	ErrAddressTypeReadOnly      error = errors.New("address type is read-only")
	ErrAddressTypeInUse         error = errors.New("address type is used by one or more entities")
	ErrEmailTypeNotFound        error = errors.New("email type not found")
	ErrEmailTypeDuplicateKey    error = errors.New("email type with same key already exists")
	ErrEmailTypeReadOnly        error = errors.New("email type is read-only")
	ErrEmailTypeInUse           error = errors.New("email type is used by one or more entities")
	ErrPhoneTypeNotFound        error = errors.New("phone type not found")
	ErrPhoneTypeDuplicateKey    error = errors.New("phone type with same key already exists")
	ErrPhoneTypeReadOnly        error = errors.New("phone type is read-only")
	ErrPhoneTypeInUse           error = errors.New("phone type is used by one or more entities")
	ErrUriTypeNotFound          error = errors.New("uri type not found")
	ErrUriTypeDuplicateKey      error = errors.New("uri type with same key already exists")
	ErrUriTypeReadOnly          error = errors.New("uri type is read-only")
	ErrUriTypeInUse             error = errors.New("uri type is used by one or more entities")
	ErrContactTitleNotFound     error = errors.New("contact title not found")
	ErrContactTitleDuplicateKey error = errors.New("contact title with same key already exists")
	ErrContactTitleReadOnly     error = errors.New("contact title is read-only")
	ErrContactTitleInUse        error = errors.New("contact title is used by one or more entities")
	ErrJobTitleNotFound         error = errors.New("job title not found")
	ErrJobTitleDuplicateKey     error = errors.New("job title with same key already exists")
	ErrJobTitleReadOnly         error = errors.New("job title is read-only")
	ErrJobTitleInUse            error = errors.New("job title is used by one or more entities")
	ErrCompanyTypeNotFound      error = errors.New("company type not found")
	ErrCompanyTypeDuplicateKey  error = errors.New("company type with same key already exists")
	ErrCompanyTypeReadOnly      error = errors.New("company type is read-only")
	ErrCompanyTypeInUse         error = errors.New("company type is used by one or more entities")
	ErrIndustryNotFound         error = errors.New("industry not found")
	ErrIndustryDuplicateKey     error = errors.New("industry with same key exists")
	ErrIndustryReadOnly         error = errors.New("industry is read-only")
	ErrIndustryInUse            error = errors.New("industry is used by one or more entities")
)
